//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.28 at 11:31:00 PM CET 
//


package com.example.systemconfigurationparametersmanagerapi.svconf;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="svConfInfo" type="{http://www.example.com/systemconfigurationparametersmanagerapi/svConf}svConfInfo"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "svConfInfo"
})
@XmlRootElement(name = "getSvConfResponse")
public class GetSvConfResponse {

    @XmlElement(required = true)
    protected SvConfInfo svConfInfo;

    /**
     * Gets the value of the svConfInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SvConfInfo }
     *     
     */
    public SvConfInfo getSvConfInfo() {
        return svConfInfo;
    }

    /**
     * Sets the value of the svConfInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SvConfInfo }
     *     
     */
    public void setSvConfInfo(SvConfInfo value) {
        this.svConfInfo = value;
    }

}
