//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.28 at 11:31:00 PM CET 
//


package com.example.systemconfigurationparametersmanagerapi.svconf;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.systemconfigurationparametersmanagerapi.svconf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.systemconfigurationparametersmanagerapi.svconf
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddSvConfRequest }
     * 
     */
    public AddSvConfRequest createAddSvConfRequest() {
        return new AddSvConfRequest();
    }

    /**
     * Create an instance of {@link SvConfInfo }
     * 
     */
    public SvConfInfo createSvConfInfo() {
        return new SvConfInfo();
    }

    /**
     * Create an instance of {@link AddSvConfResponse }
     * 
     */
    public AddSvConfResponse createAddSvConfResponse() {
        return new AddSvConfResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link GetSvConfRequest }
     * 
     */
    public GetSvConfRequest createGetSvConfRequest() {
        return new GetSvConfRequest();
    }

    /**
     * Create an instance of {@link GetSvConfResponse }
     * 
     */
    public GetSvConfResponse createGetSvConfResponse() {
        return new GetSvConfResponse();
    }

    /**
     * Create an instance of {@link UpdateSvConfRequest }
     * 
     */
    public UpdateSvConfRequest createUpdateSvConfRequest() {
        return new UpdateSvConfRequest();
    }

    /**
     * Create an instance of {@link UpdateSvConfResponse }
     * 
     */
    public UpdateSvConfResponse createUpdateSvConfResponse() {
        return new UpdateSvConfResponse();
    }

    /**
     * Create an instance of {@link DeleteSvConfRequest }
     * 
     */
    public DeleteSvConfRequest createDeleteSvConfRequest() {
        return new DeleteSvConfRequest();
    }

    /**
     * Create an instance of {@link DeleteSvConfResponse }
     * 
     */
    public DeleteSvConfResponse createDeleteSvConfResponse() {
        return new DeleteSvConfResponse();
    }

}
