//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.28 at 11:31:00 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.example.com/systemconfigurationparametersmanagerapi/svConf")
package com.example.systemconfigurationparametersmanagerapi.svconf;
